---
- name: enable tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true

- name: restart tomcat instance
  service:
    name: tomcat
    state: restarted