apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: k8s-dev0.anilens.com
spec:
  api:
    loadBalancer:
      additionalSecurityGroups:
      - '[sg-0d3f24ed32e91d61a]'
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://terraform-state-20190721003000325900000001/k8s-dev0.anilens.com
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    - instanceGroup: master-eu-west-2b
      name: b
    - instanceGroup: master-eu-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-eu-west-2a
      name: a
    - instanceGroup: master-eu-west-2b
      name: b
    - instanceGroup: master-eu-west-2c
      name: c
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.10.6
  masterPublicName: api.k8s-dev0.anilens.com
  networkCIDR: 10.0.0.0/16
  networkID: vpc-0565e5ee7cb1c25a0
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  - id: subnet-031024c2c02050582
    name: utility-eu-west-2a
    type: Utility
    zone: eu-west-2a
  - id: subnet-0140e69dc3f5d1398
    name: utility-eu-west-2b
    type: Utility
    zone: eu-west-2b
  - id: subnet-0980760266a6ab7e7
    name: utility-eu-west-2c
    type: Utility
    zone: eu-west-2c
  - egress: eu-west-2a
    id: subnet-0c0e17dee217f4fcf
    name: eu-west-2a
    type: Private
    zone: eu-west-2a
  - egress: eu-west-2b
    id: subnet-0b8b5d079a04d3b3e
    name: eu-west-2b
    type: Private
    zone: eu-west-2b
  - egress: eu-west-2c
    id: subnet-0b72d912113d6808e
    name: eu-west-2c
    type: Private
    zone: eu-west-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-dev0.anilens.com
  name: master-eu-west-2a
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-2a
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-dev0.anilens.com
  name: master-eu-west-2b
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-2b
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-dev0.anilens.com
  name: master-eu-west-2c
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - eu-west-2c
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-dev0.anilens.com
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.micro
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  - eu-west-2a
  - eu-west-2b
  - eu-west-2c
