---
  - name: Configure Apache
    lineinfile:
      backup: yes
      path: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
      regex: "{{ items.regexp }}"
      line: "{{ items.line }}"
      state: present
    with_items: "{{ apache_ports_configuration_items }}"
    notify: restart apache

  - name: Check Certificates existance
    stat:
      path: "{{ item.certificate_file }}"
      register: apache_ssl_certificates
    with_items: "{{ apache_vhosts_ssl }}"
  
  - debug:
      msg: "{{ apache_ssl_certificates.stat }}"
  
  - name: add apache vhosts configuration
    template:
      src: "{{ apache_vhosts_template }}"
      dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
      mode: 0644
      owner: root
      group: root
    notify: restart apache
    when: apache_create_vhosts
