---
  - name: Configure Apache
    lineinfile:
      backup: yes
      path: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
      regex: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items: "{{ apache_ports_configuration_items }}"
    notify: restart apache

  - name: Check Certificates existance
    stat:
      path: "{{ item.certificate_file }}"
    with_items: "{{ apache_vhosts_ssl }}"
    register: apache_ssl_certificates
    
  - name: Fail if return code is not 0
    fail:
      msg: "{{ item.stat.path }} doesn't exists"
    when: not item.stat.exists
    with_items: "{{ apache_ssl_certificates.results }}"

  - debug:
      var: item.stat.path
    with_items: "{{ apache_ssl_certificates.results }}"

  - name: add apache vhosts configuration
    template:
      src: "{{ apache_vhosts_template }}"
      dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
      mode: 0644
      owner: root
      group: root
    notify: restart apache
    when: apache_create_vhosts
