---
- name: Install Gitlab
  hosts: tag_Type_Controller
  become: true

  tasks:
    - name: Install Dependencies
      package:
        name: "{{ item }}"
      with_items: [ postfix, ca-certificates, curl, openssh-server, git, openssl]
      when: ansible_distribution == 'Amazon'
    
    - name: Install Gitlab Repository
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
        dest: /tmp/gitlab_install_repository.sh
        mode: 0777
    
    - name: Run Gitlab Repository Script
      shell: /tmp/gitlab_install_repository.sh

    - name: Install GitLab CE
      package:
        name:
          - gitlab-ce
        state: latest
        update_cache: yes
    
    - name: Restart with reconfigure
      command: gitlab-ctl reconfigure

    - name: GitLab Restart with restart
      command: gitlab-ctl restart

    - name: GitLab gitlab-runsvdir status
      command: service gitlab-runsvdir status