---
  - name: Ansible with Jinja2
    hosts: localhost
    environment:
      SOME: value
    vars:
      users:
        alice:
          name: Alice Appleworth
          telephone: 123-456-7890
        bob:
          name: Bob Bananarama
          telephone: 987-654-3210

    tasks:
      - name: If Statement
        debug:
          msg: >
                --== Ansible with Jinja2 Templating ==--
                {# if the Ansible Host name is #}
                {% set pumba = 'gundu' %}
                {% if ansible_distribution == "MacOSX" %}
                  Running on {{ ansible_hostname }}, Variable set {{ pumba }}
                {% endif %}
      - name: For loop
        debug:
          msg: >
                {# Looping through IPv4 #}
                {{ ansible_default_ipv4 | to_nice_json(indent=2) }}
                {% for key,value in ansible_default_ipv4.items() %}
                    entry {{ loop.index }} Value of {{ key }} is {{ value }}
                {% endfor %}
      - name: Print phone records
        debug:
          msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
        with_dict: "{{ users }}"

      - debug: "{{ hostvars }}"
      - debug: "{{ lookup('env','HOME') }}"