---
  - hosts: tag_Type_Ansible
    become: true
    gather_facts: true

    tasks:
      - name: Install Packages
        package: 
          name: "{{ item }}"
          state: present
        with_items:  [apache2]
      
      - name: Start Apache Service
        service:
          name: apache2
          state: started
          enabled: yes
