- name: 'downloading Java 11 JDK file {{ java_download_filename }}'
  get_url:
    url: '{{ java_download_url }}'
    validate_certs: false
    headers: Cookie:oraclelicense=accept-securebackup-cookie
    dest: '{{ java_archive }}'
    mode: 0644
  when: ( not java_is_download_file.stat.exists or java_installer_force_overwrite ) and java_installer_force_download and not java_installer_local

- name: 'uncompressing {{ java_download_filename }} file'
  unarchive:
    src: '{{ java_archive }}'
    dest: '{{ java_usr_folder }}'
    owner: root
    group: root
    copy: false
  when: not java_installed.stat.exists or force_java_install

- name: remove downloaded file
  file:
    path: '{{ java_archive }}'
    state: absent
  when: not java_installer_keep