apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{.kubernetes_cluster_name.value}}
spec:
  api:
    loadBalancer:
      type: Public
      additionalSecurityGroups: {{.k8s_api_http.value}}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.tfstate_bucket.value}}/{{.kubernetes_cluster_name.value}}
  # Create one etcd member per AZ
  etcdClusters:
  - etcdMembers:
  {{range $i, $az := .avlb_zones.value}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.kube_region.value "" }} {{/* converts eu-west-2a to a */}}
  {{end}}
    name: main
  - etcdMembers:
  {{range $i, $az := .avlb_zones.value}}
    - instanceGroup: master-{{.}}
      name: {{. | replace $.kube_region.value "" }} {{/* converts eu-west-2a to a */}}
  {{end}}
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubernetesVersion: 1.10.6
  masterPublicName: api.{{.kubernetes_cluster_name.value}}
  networkCIDR: {{.kube_cidr.value}}
  networkID: {{.kube_vpc.value}}
  networking:
    canal: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  subnets:
  # Public (utility) subnets, one per AZ
  {{range $i, $id := .kube_public_subnets.value}}
  - id: {{.}}
    name: utility-{{index $.avlb_zones.value $i}}
    type: Utility
    zone: {{index $.avlb_zones.value $i}}
  {{end}}
  # Private subnets, one per AZ
  {{range $i, $id := .kube_private_subnets.value}}
  - id: {{.}}
    name: {{index $.avlb_zones.value $i}}
    type: Private
    zone: {{index $.avlb_zones.value $i}}
    egress: {{index $.nat_gateway_ids.value 0}}
  {{end}}
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---

# Create one master per AZ
{{range .avlb_zones.value}}
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{$.kubernetes_cluster_name.value}}
  name: master-{{.}}
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - {{.}}
---
  {{end}}

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.kubernetes_cluster_name.value}}
  name: nodes
spec:
  image: kope.io/k8s-1.10-debian-stretch-amd64-hvm-ebs-2018-08-17
  kubernetesVersion: 1.10.6
  machineType: t2.micro
  maxSize: 2
  minSize: 1
  role: Node
  subnets:
  {{range .avlb_zones.value}}
  - {{.}}
  {{end}}